name: Multi-platform Release of cppfront
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compiler name & version
        run: cl.exe
      - name: Build
        run: cl.exe source/cppfront.cpp -std:c++latest -MD -EHsc -experimental:module -W4 -WX
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: cppfront-windows.exe
          path: cppfront.exe
          overwrite: true

  build-unix-like:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        compiler: [g++-12, clang++-18]
        cxx-std: ['c++20']
        include:
          - runs-on: macos-latest
            compiler: clang++
            cxx-std: 'c++20'
          - runs-on: ubuntu-latest
            compiler: clang++-18
            cxx-std: 'c++20'
    runs-on: ${{ matrix.runs-on }}
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: -std=${{ matrix.cxx-std }} -Wall -Wextra -Wold-style-cast -Wunused-parameter -Wpedantic -Werror -pthread -Wno-unknown-warning -Wno-unknown-warning-option
    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      if: startsWith(matrix.runs-on, 'ubuntu')
      run: sudo apt-get install -y $CXX
    - name: Compiler name & version
      run: $CXX --version
    - name: Build
      run: $CXX source/cppfront.cpp $CXXFLAGS -o cppfront
    - name: Upload binary (linux)
      if: startsWith(matrix.runs-on, 'ubuntu') && startsWith(matrix.compiler, 'clang')
      uses: actions/upload-artifact@v4
      with:
        name: cppfront-linux
        path: cppfront
        overwrite: true
    - name: Upload binary (macos)
      if: startsWith(matrix.runs-on, 'macos') && startsWith(matrix.compiler, 'clang')
      uses: actions/upload-artifact@v4
      with:
        name: cppfront-macos
        path: cppfront
        overwrite: true
        
  release:
    needs: [build-windows, build-unix-like]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag -l "v*" --sort=-creatordate | head -n 1)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: ./binaries

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.TAG }}
          name: ${{ env.TAG }}
          artifacts: "./binaries/*"
          body: |
            Release for ${{ env.TAG }} (from ${{ github.sha }})
          replacesArtifacts: true
          allowUpdates: true

